version: 2.1
# orbs:
#   ruby: circleci/ruby@0.1.2
references:
  ruby_envs: &ruby_envs
    environment:
      BUNDLE_PATH: vendor/bundle
      DATABASE_HOSTNAME: 127.0.0.1
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      BUNDLER_VERSION: 2.1.4
      RAILS_ENV: test
  mysql_envs: &mysql_envs
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
jobs:
  test_rspec:
    docker:
      - image: hatd/circle-ci:3.0
        <<: *ruby_envs
      - image: mysql:5.7.33
        <<: *mysql_envs
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: Bundle Install
          command: bundle check --path $BUNDLE_PATH || bundle install --jobs=4 --retry=3 --path $BUNDLE_PATH
      - run:
          name: Database setup
          command: RAILS_ENV=test bundle exec rails db:drop db:create
      - run:
          name: Run Migrate
          command: RAILS_ENV=test bundle exec rails db:migrate
      - run:
          name: Build assets
          command: bundle exec rails assets:precompile
      - run:
          name: Rspec test
          command: bundle exec rubocop
      - run:
          name: Rspec test
          command: bundle exec rspec spec/
workflows:
  version: 2
  build_and_test:
    jobs:
    - test_rspec
