name: Rails
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_rspec:
    name: Test Rspec
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7.33
        env:
          DATABASE_USERNAME: root
          DATABASE_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
        ports: ['3306:3306']
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      BUNDLE_PATH: vendor/bundle
      DATABASE_HOSTNAME: 127.0.0.1
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      BUNDLER_VERSION: 2.1.4
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v1
      - uses: docker://hatd/circle-ci:4.0
      - name: Bundle install
        run: |
          bundle install
